// Copyright (c) 2024, Awessets

using UnityEngine;

namespace MergeIt.Editor
{
    public static class Constants
    {
        public static Vector2 NodeCreationOffset = new(280f, 0f);

        public const string LevelEditorResourcesRoot = "MergeLevelEditor";
        public const string EvolutionsEditorResourcesRoot = "MergeEvolutionsEditor";
        public const string InspectorResourcesRoot = "MergeCustomInspectors";
        public const string EvolvedFromPort = "evolved from";
        public const string EvolvePort = "evolve";     
        public const string EvolutionRootPort = "evolution of";     
        public const string NamePort = "name";     
        public const string HasNamePort = "has name";     
        public const string GeneratedByPort = "generated by";
        public const string GeneratePort = "generate";
    }
}